/**
 * TR→RU UI sözlüğü üretir. Kaynak: glossary + src taraması.
 * Çalıştır: node scripts/build-ui-ru.mjs
 */
import fs from "fs";
import path from "path";

/** Uzun ifadeler önce — runtime da aynı sırayı kullanır. */
const G = {
  "Genel Bakış": "Обзор",
  "Kasa bakiyesi nasıl okunur?": "Как читать баланс кассы?",
  "Bu Ay Bekleyen Ödeme": "Ожидает выплаты в этом месяце",
  "Bu Ay Bekleyen Ödemeler": "Ожидающие выплаты в этом месяце",
  "Geri ödenmemiş avans bakiyesi": "Непогашенный остаток аванса",
  "İçerik Harcaması (Bu Ay)": "Расход на контент (этот месяц)",
  "Net Kar (yıllık tahmin)": "Чистая прибыль (годовая оценка)",
  "Toplam Gelir (yıllık)": "Доход всего (год)",
  "Bordrolu Yayıncı": "Стримеры в ведомости",
  "Aktif Marka": "Активные бренды",
  "Takip Edilen Link": "Отслеживаемые ссылки",
  "Otomatik izlenen sosyal medya linkleri": "Автоматически отслеживаемые ссылки соцсетей",
  "Gelir / Gider Analizi": "Анализ доходов / расходов",
  "Mali Dağılım": "Финансовое распределение",
  "Aylık Gelir Kırılımı": "Разбивка дохода по месяцам",
  "Dış + İç proje gelirleri": "Внешние + внутренние доходы",
  "Son Aktiviteler": "Последние действия",
  "Güncel durum bildirimleri": "Актуальные уведомления",
  "Tüm yayıncı gönderimleri onaylanmış": "Все заявки стримеров одобрены",
  "Bekleyen inceleme yok": "Нет ожидающих проверок",
  "Tüm içerik harcamaları kapalı": "Все расходы на контент закрыты",
  "Bekleyen rapor yok": "Нет ожидающих отчётов",
  "Ödeme Raporu hazır": "Отчёт по выплатам готов",
  "Ramiz cüzdan toplam": "Итого кошелёк Рамиза",
  "Ramiz cüzdan (otomatik)": "Кошелёк Рамиза (авто)",
  "Ramiz cüzdanı": "Кошелёк Рамиза",
  "Kar marjı": "Маржа прибыли",
  "Tam kadro": "Полный состав",
  "İç Proje": "Внутренний проект",
  "Dış Firmalar": "Внешние компании",
  "Bu Ay": "Этот месяц",
  "Bu ay": "Этот месяц",
  "mali özet": "финансовая сводка",
  "OrkunTilki bu uygulamayı geliştirdi.": "OrkunTilki разработал это приложение.",
  "yayıncı paneli · yönetici görünümü": "панель стримера · вид администратора",
  "marka paneli · yönetici görünümü": "панель бренда · вид администратора",
  "İçerik Harcamaları": "Расходы на контент",
  "İçerik harcamaları": "Расходы на контент",
  "İçerik Harcaması": "Расход на контент",
  "İçerik harcaması": "Расход на контент",
  "Haftalık Takvim": "Недельный календарь",
  "Haftalık takvim": "Недельный календарь",
  "Haftalık plan": "Недельный план",
  "Haftalık yayın planı": "Недельный план эфиров",
  "Haftalık paylaşım achievement": "Недельный achievement публикаций",
  "Premium keşif": "Premium-поиск",
  "Ödeme Raporu": "Отчёт по выплатам",
  "Kontrol Paneli": "Панель управления",
  "Onay Merkezi": "Центр одобрений",
  "Prim Havuzu": "Пул премий",
  "Bildirim Merkezi": "Центр уведомлений",
  "Landing galeri": "Галерея лендинга",
  "Dış Gelir (Geçmiş)": "Внешний доход (история)",
  "Dış Gelir": "Внешний доход",
  "İç Gelir": "Внутренний доход",
  "Tüm markalar": "Все бренды",
  "Tüm Markalar": "Все бренды",
  "Tüm yayıncılar": "Все стримеры",
  "Tüm Yayıncılar": "Все стримеры",
  "Tüm durumlar": "Все статусы",
  "Tüm kategoriler": "Все категории",
  "Tüm Kategoriler": "Все категории",
  "Tüm aylar": "Все месяцы",
  "Tüm Aylar": "Все месяцы",
  "Tüm linkler": "Все ссылки",
  "Tüm roller": "Все роли",
  "Tüm platformlar": "Все платформы",
  "Tüm kullanıcılar": "Все пользователи",
  "Tüm çalışanlar": "Все сотрудники",
  "Tüm Çalışanlar": "Все сотрудники",
  "Tüm anlaşmalar": "Все сделки",
  "Tüm görevler": "Все задачи",
  "Tüm tipler": "Все типы",
  "Tüm kaynaklar": "Все источники",
  "Tüm kasalar": "Все кассы",
  "Tüm kalemler": "Все позиции",
  "Ana Yönetici": "Главный админ",
  "Ana yönetici": "Главный админ",
  "Yönetici paneline dön": "Вернуться в админ-панель",
  "Yayıncı Paneli": "Панель стримера",
  "Yayıncı paneli": "Панель стримера",
  "Yayıncı havuzu": "Пул стримеров",
  "Yayıncı Havuzu": "Пул стримеров",
  "Marka linkleri": "Ссылки брендов",
  "Marka Linkleri": "Ссылки брендов",
  "Toplam İzlenme": "Всего просмотров",
  "Toplam izlenme": "Всего просмотров",
  "Aylık izlenme": "Просмотры за месяц",
  "Aylık İzlenme": "Просмотры за месяц",
  "İzlenme özeti": "Сводка просмотров",
  "İzlenme grafikleri": "Графики просмотров",
  "İzlenme Snapshot": "Снимок просмотров",
  "İzlenme Sayısı": "Число просмотров",
  "Link izlenme özeti": "Сводка просмотров ссылок",
  "Önceki aya göre değişim": "Изменение к прошлому месяцу",
  "Önceki aya göre": "К прошлому месяцу",
  "Önceki ay": "Прошлый месяц",
  "Önceki hafta": "Прошлая неделя",
  "Önceki gün": "Вчера",
  "Sonraki gün": "Завтра",
  "Sonraki ay": "Следующий месяц",
  "Sonraki aya ayrılan": "Отложено на след. месяц",
  "Bugüne dön": "К сегодня",
  "Panele geri dön": "Назад в панель",
  "Aramayı temizle": "Очистить поиск",
  "Filtreleri sıfırla": "Сбросить фильтры",
  "Okundu işaretle": "Отметить прочитанным",
  "Ödendi işaretle": "Отметить оплаченным",
  "PIN sıfırla": "Сбросить PIN",
  "Linki aç": "Открыть ссылку",
  "Kanıtı aç": "Открыть доказательство",
  "Metriği yenile": "Обновить метрику",
  "API ile yenile": "Обновить через API",
  "CSV içe aktar": "Импорт CSV",
  "Aylık KPI gir": "Ввести KPI месяца",
  "Aylık hedef": "Месячная цель",
  "Aylık rapor": "Месячный отчёт",
  "Aylık Tutar": "Сумма в месяц",
  "Aylık Gelir": "Доход за месяц",
  "Aylık maliyet": "Месячные затраты",
  "Net yatırım": "Чистые инвестиции",
  "Net Ödenecek": "К выплате (нетто)",
  "Net ödenecek": "К выплате (нетто)",
  "Temel maaş": "Базовая зарплата",
  "Temel Maaş": "Базовая зарплата",
  "Kira desteği": "Жилищная поддержка",
  "Kira Desteği": "Жилищная поддержка",
  "Açık Avans": "Открытый аванс",
  "Açık avans": "Открытый аванс",
  "Ödeme tarihi": "Дата оплаты",
  "Ödeme Tarihi": "Дата оплаты",
  "Başlangıç tarihi": "Дата начала",
  "Başlangıç Tarihi": "Дата начала",
  "Bitiş tarihi": "Дата окончания",
  "Kullanıcı adı": "Имя пользователя",
  "Kullanıcı Adı": "Имя пользователя",
  "Görünen ad": "Отображаемое имя",
  "Marka adı": "Название бренда",
  "Aktif Anlaşma": "Активная сделка",
  "Aktif anlaşma": "Активная сделка",
  "Henüz bildirim yok": "Уведомлений пока нет",
  "Henüz bildirim yok.": "Уведомлений пока нет.",
  "Kayıt yok": "Нет записей",
  "Kayıt yok.": "Нет записей.",
  "Kayıt bulunamadı": "Записи не найдены",
  "Erişim Yok": "Нет доступа",
  "Yükleniyor…": "Загрузка…",
  "Yükleniyor...": "Загрузка…",
  "Görevler yükleniyor…": "Задачи загружаются…",
  "Veriler yükleniyor": "Данные загружаются",
  "Harcama Gönder": "Отправить расход",
  "Mesaj / Bildirim Gönder": "Отправить сообщение",
  "Bilgi İste": "Запросить информацию",
  "Bilgi İsteniyor": "Нужна информация",
  "Bekleyen İnceleme": "Ожидает проверки",
  "İncelemede": "На проверке",
  "Geri çekildi": "Отозвано",
  "Tamamlandı": "Завершено",
  "Tamamlanmış": "Завершено",
  "Duraklatıldı": "Приостановлено",
  "Duraklatılmış": "Приостановлено",
  "İptal edildi": "Отменено",
  "Atanmamış": "Не назначено",
  "Atanmadı": "Не назначено",
  "— Atanmadı": "— Не назначено",
  "— Seçin —": "— Выберите —",
  "— Marka seçilmedi —": "— Бренд не выбран —",
  "Seçiniz": "Выберите",
  "Seçin…": "Выберите…",
  "Seçin...": "Выберите…",
  "Marka seç…": "Выберите бренд…",
  "Marka seçin…": "Выберите бренд…",
  "Yayıncı ara…": "Поиск стримера…",
  "İşlem ara...": "Поиск операций…",
  "Çalışan ara...": "Поиск сотрудника…",
  "Kullanıcı ara": "Поиск пользователя",
  "Dış gelir ara": "Поиск внешнего дохода",
  "İçerik harcaması ara": "Поиск расходов на контент",
  "Denetim kaydı ara": "Поиск журнала аудита",
  "Okundu işaretle": "Отметить прочитанным",
  "Tümü": "Все",
  "tümü": "все",
  "Sil": "Удалить",
  "Düzenle": "Изменить",
  "İptal": "Отмена",
  "Kaydet": "Сохранить",
  "Ekle": "Добавить",
  "Aç": "Открыть",
  "Kapat": "Закрыть",
  "Geri": "Назад",
  "İleri": "Далее",
  "Gönder": "Отправить",
  "Onayla": "Одобрить",
  "Reddet": "Отклонить",
  "Kaldır": "Убрать",
  "Çıkar": "Исключить",
  "Çıkış": "Выйти",
  "Giriş": "Войти",
  "Ara": "Поиск",
  "Seç": "Выбрать",
  "Seçildi": "Выбрано",
  "Yönet": "Управлять",
  "İndir": "Скачать",
  "Yükle": "Загрузить",
  "Sıfırla": "Сбросить",
  "Üret": "Сгенерировать",
  "Öde": "Оплатить",
  "Filtre": "Фильтр",
  "Rapor": "Отчёт",
  "Özet": "Сводка",
  "Detay": "Детали",
  "İşlem": "Действие",
  "Aktif": "Активен",
  "aktif": "активен",
  "Pasif": "Неактивен",
  "pasif": "неактивен",
  "Kapalı": "Выкл.",
  "Açık": "Вкл.",
  "Yeni": "Новый",
  "YENİ": "НОВОЕ",
  "Onaylı": "Одобрено",
  "Ödendi": "Оплачено",
  "Ödenen": "Оплачено",
  "Ödenmiş": "Оплачено",
  "Gecikmiş": "Просрочено",
  "Beklemede": "В ожидании",
  "Yüksek": "Высокий",
  "Düşük": "Низкий",
  "Normal": "Обычный",
  "Orta": "Средний",
  "Diğer": "Другое",
  "İzlenme": "Просмотры",
  "İzlenmeler": "Просмотры",
  "izlenme": "просмотры",
  "Beğeni": "Лайки",
  "Tıklama": "Клики",
  "Paylaşım": "Публикация",
  "Paylaşımlar": "Публикации",
  "Yayıncı": "Стример",
  "Yayıncılar": "Стримеры",
  "yayıncı": "стример",
  "Marka": "Бренд",
  "Markalar": "Бренды",
  "marka": "бренд",
  "Yönetici": "Админ",
  "Yöneticiler": "Админы",
  "Denetçi": "Аудитор",
  "Denetçiler": "Аудиторы",
  "Denetim": "Аудит",
  "Kullanıcılar": "Пользователи",
  "Kullanıcı": "Пользователь",
  "Görevler": "Задачи",
  "Görev": "Задача",
  "Maaşlar": "Зарплаты",
  "Maaş": "Зарплата",
  "Kasa": "Касса",
  "Prim": "Премия",
  "Takvim": "Календарь",
  "Bildirimler": "Уведомления",
  "Bildirim": "Уведомление",
  "Anlaşma": "Сделка",
  "Anlaşmalar": "Сделки",
  "Teklif": "Оффер",
  "Teklifler": "Офферы",
  "Postlar": "Посты",
  "Post": "Пост",
  "Hesaplar": "Аккаунты",
  "Hesap": "Аккаунт",
  "Profil": "Профиль",
  "İstatistikler": "Статистика",
  "Operatörler": "Операторы",
  "Operatör": "Оператор",
  "Personel": "Персонал",
  "Departmanlar": "Отделы",
  "Departman": "Отдел",
  "Faturalar": "Счета",
  "Fatura": "Счёт",
  "Bordro": "Ведомость",
  "Muhasebe": "Бухгалтерия",
  "Ödemeler": "Выплаты",
  "Ödeme": "Выплата",
  "Kampanyalar": "Кампании",
  "Kampanya": "Кампания",
  "Giderler": "Расходы",
  "Gider": "Расход",
  "Gelir": "Доход",
  "Planlanan": "План",
  "Onaylar": "Одобрения",
  "Açıklama": "Описание",
  "Başlık": "Заголовок",
  "Başlangıç": "Начало",
  "Bitiş": "Конец",
  "Tarih": "Дата",
  "Saat": "Время",
  "Gün": "День",
  "Ay": "Месяц",
  "Yıl": "Год",
  "Yıllık": "Годовой",
  "Aylık": "Месячный",
  "Haftalık": "Недельный",
  "Günlük": "Дневной",
  "Bugün": "Сегодня",
  "bugün": "сегодня",
  "Toplam": "Итого",
  "TOPLAM": "ИТОГО",
  "Tür": "Тип",
  "Durum": "Статус",
  "Kategori": "Категория",
  "Platform": "Платформа",
  "Link": "Ссылка",
  "URL": "URL",
  "Bütçe": "Бюджет",
  "Ücret": "Ставка",
  "Tutar": "Сумма",
  "Değer": "Значение",
  "Adet": "Кол-во",
  "Sıra": "Порядок",
  "Sıralama": "Сортировка",
  "Sırala": "Сортировать",
  "Öncelik": "Приоритет",
  "Not": "Заметка",
  "Notlar": "Заметки",
  "Kanıt": "Доказательство",
  "Amaç": "Назначение",
  "Etiket": "Метка",
  "Rol": "Роль",
  "Yetki": "Право",
  "Yetkiler": "Права",
  "Dil": "Язык",
  "Ülke": "Страна",
  "Pazar": "Рынок",
  "Takipçi": "Подписчики",
  "Etkileşim": "Вовлечённость",
  "İçerik": "Контент",
  "Yayın": "Эфир",
  "Yatırım": "Депозит",
  "Çekim": "Вывод",
  "Kayıt": "Регистрация",
  "Kayıtlar": "Записи",
  "Dönem": "Период",
  "Hedef": "Цель",
  "Büyüme": "Рост",
  "Pay": "Доля",
  "Grafik": "График",
  "Tablo": "Таблица",
  "Liste": "Список",
  "Kart": "Карточка",
  "Ara...": "Поиск...",
  "Ara…": "Поиск…",
  "Temizle": "Очистить",
  "Uygula": "Применить",
  "Vazgeç": "Отмена",
  "Tamam": "ОК",
  "Evet": "Да",
  "Hayır": "Нет",
  "Yok": "Нет",
  "Var": "Есть",
  "Boş": "Пусто",
  "Hepsi": "Все",
  "Hiç": "Нет",
  "hiçbiri": "ничего",
  "veya": "или",
  "ve": "и",
  "ile": "с",
  "için": "для",
  "göre": "по",
  "kadar": "до",
  "sonra": "после",
  "önce": "до",
  "üstünde": "выше",
  "altında": "ниже",
  "Ocak": "Январь",
  "Şubat": "Февраль",
  "Mart": "Март",
  "Nisan": "Апрель",
  "Mayıs": "Май",
  "Haziran": "Июнь",
  "Temmuz": "Июль",
  "Ağustos": "Август",
  "Eylül": "Сентябрь",
  "Ekim": "Октябрь",
  "Kasım": "Ноябрь",
  "Aralık": "Декабрь",
  "Pazartesi": "Понедельник",
  "Salı": "Вторник",
  "Çarşamba": "Среда",
  "Perşembe": "Четверг",
  "Cuma": "Пятница",
  "Cumartesi": "Суббота",
  "Pazar": "Воскресенье",
  "Yüklenemedi": "Не удалось загрузить",
  "Güncellenemedi": "Не удалось обновить",
  "Güncelle": "Обновить",
  "Güncel": "Актуально",
  "Kaydetilemedi": "Не удалось сохранить",
  "Sunucu hatası": "Ошибка сервера",
  "Ağ hatası": "Ошибка сети",
  "Oturum gerekli": "Нужна сессия",
  "Erişim yok": "Нет доступа",
  "Bulunamadı": "Не найдено",
  "Zorunlu": "Обязательно",
  "Opsiyonel": "Необязательно",
  "İsteğe bağlı": "По желанию",
  "opsiyonel": "необязательно",
  "Onboarding": "Онбординг",
  "Moderatör": "Модератор",
  "Koordinatör": "Координатор",
  "Editör": "Редактор",
  "Destek": "Поддержка",
  "Finans": "Финансы",
  "Muhasebe": "Бухгалтерия",
  "Sistem": "Система",
  "Kontrol": "Контроль",
  "Yayın": "Эфир",
  "Hesap": "Аккаунт",
  "Ekip": "Команда",
  "Genel": "Общее",
  "İş Birliği": "Сотрудничество",
  "Büyüme": "Рост",
  "Planlandı": "Запланировано",
  "Yapılacak": "К выполнению",
  "İnceleme": "Проверка",
  "Önizleme": "Предпросмотр",
  "Geniş ekran": "Широкий экран",
  "Liste görünümü": "Вид списком",
  "Kart görünümü": "Вид карточками",
  "Daha az göster": "Показать меньше",
  "Detayları göster": "Показать детали",
  "Menüyü kapat": "Закрыть меню",
  "Menüyü aç": "Открыть меню",
  "Gizli mod": "Скрытый режим",
  "Aktif marka": "Активный бренд",
  "Çıkış Yap": "Выйти",
  "Kayıt Ol": "Регистрация",
  "Giriş Yap": "Войти",
  "Şifre": "Пароль",
  "Parola": "Пароль",
  "E-posta": "Эл. почта",
  "Telefon": "Телефон",
  "Ad": "Имя",
  "Soyad": "Фамилия",
  "İsim": "Имя",
  "Şirket": "Компания",
  "Website": "Сайт",
  "Adres": "Адрес",
  "Cüzdan": "Кошелёк",
  "Bakiye": "Баланс",
  "Giriş bilgileri": "Данные входа",
  "Yeni Kullanıcı": "Новый пользователь",
  "Yeni görev": "Новая задача",
  "Yeni marka aç": "Создать бренд",
  "Çalışan Ekle": "Добавить сотрудника",
  "Operatör ekle": "Добавить оператора",
  "İşlem Ekle": "Добавить операцию",
  "Kayıt ekle": "Добавить запись",
  "Görev ekle": "Добавить задачу",
  "Hesabı gir": "Войти в аккаунт",
  "Pasifleştir": "Деактивировать",
  "Arşivle": "В архив",
  "Kopyala": "Копировать",
  "Yazdır": "Печать",
  "Dışa aktar": "Экспорт",
  "İçe aktar": "Импорт",
  "Bağlantı": "Связь",
  "Bağlantılar": "Связи",
  "Entegrasyon": "Интеграция",
  "API & keşif": "API и поиск",
  "Canlı izlenme": "Живые просмотры",
  "Canlı veri": "Живые данные",
  "Hazır": "Готово",
  "Hazır senaryolar": "Готовые сценарии",
  "Senaryolar": "Сценарии",
  "Senaryo": "Сценарий",
  "Kurallar": "Правила",
  "Dağıtım": "Распределение",
  "Akış": "Поток",
  "Geçmiş": "История",
  "Geçmiş aylar": "Прошлые месяцы",
  "Geçmiş Aylar": "Прошлые месяцы",
  "Anasayfa": "Главная",
  "Operasyon özeti": "Сводка операций",
  "Operasyon": "Операции",
  "Raporlar": "Отчёты",
  "Yayıncı takvimi": "Календарь стримеров",
  "Marka profili": "Профиль бренда",
  "Havuz profili": "Профиль пула",
  "Ödeme planı": "План оплат",
  "Görev & Takip": "Задачи",
  "Mesai & Mola": "Смены и паузы",
  "Personel duyuruları": "Объявления",
  "Ekip & yetkiler": "Команда и права",
  "Denetim Özeti": "Сводка аудита",
  "Marka İzlenme": "Просмотры бренда",
  "Yetişkin İçerik": "Adult-контент",
  "Site Videoları": "Видео сайта",
  "Canlı yayın": "Прямой эфир",
  "Canlı Yayın": "Прямой эфир",
  "Reels / kısa video": "Reels / короткое видео",
  "Post / gönderi": "Пост",
  "Kısa not": "Краткая заметка",
  "Kısa ad": "Короткое имя",
  "Kısa kod": "Короткий код",
  "Görünürlük": "Видимость",
  "Hakkında": "О себе",
  "Hakkımda": "Обо мне",
  "Kategoriler": "Категории",
  "Ülke / bölge": "Страна / регион",
  "Sonuç sayısı": "Число результатов",
  "Sonuç yok": "Нет результатов",
  "Filtreye uyan içerik yok.": "Нет контента по фильтру.",
  "Eşleşen kayıt yok.": "Нет совпадений.",
  "Henüz link yok.": "Ссылок пока нет.",
  "Henüz link verisi yok.": "Данных по ссылкам пока нет.",
  "Henüz teklif yok": "Офферов пока нет",
  "Henüz anlaşma yok": "Сделок пока нет",
  "Henüz post eklemediniz": "Постов пока нет",
  "Henüz bildirim yok.": "Уведомлений пока нет.",
  "Henüz hesap eklenmedi.": "Аккаунты ещё не добавлены.",
  "Bu ay içerik yok": "В этом месяце нет контента",
  "Bu ay için veri yok": "Нет данных за этот месяц",
  "Çalışan bulunamadı": "Сотрудник не найден",
  "Marka bulunamadı": "Бренд не найден",
  "Personel bulunamadı.": "Персонал не найден.",
  "Kontak bulunamadı.": "Контакт не найден.",
  "Aktif yayıncı bulunamadı.": "Активных стримеров нет.",
  "Havuz boş": "Пул пуст",
  "Liste boş": "Список пуст",
  "Görev yok": "Нет задач",
  "Görev yok.": "Нет задач.",
  "Anlaşma yok": "Нет сделок",
  "İncele": "Проверить",
  "İncelemeyi Aç": "Открыть проверку",
  "Kasadan öde": "Оплатить из кассы",
  "Kasadan düş": "Списать с кассы",
  "Kasa İncele": "Проверить кассу",
  "Kasa yönetimi": "Управление кассой",
  "Kasa adı": "Название кассы",
  "Genel Kasa": "Общая касса",
  "Ramiz cüzdanı": "Кошелёк Рамиза",
  "TRON cüzdan": "Кошелёк TRON",
  "Zincir bakiyesi yükleniyor…": "Баланс сети загружается…",
  "Toplam Giriş": "Всего вход",
  "Toplam Çıkış": "Всего выход",
  "Karşı Taraf": "Контрагент",
  "Alıcı / gönderici": "Получатель / отправитель",
  "Ödeme sebebi": "Причина платежа",
  "Ödeme yöntemi": "Способ оплаты",
  "Ödeme yolu": "Канал выплаты",
  "Firma Adı": "Название фирмы",
  "İletişim Kişisi": "Контакт",
  "İletişim": "Контакты",
  "İşlem Sayısı": "Число операций",
  "Kategori Dağılımı": "Разбивка по категориям",
  "Tüm geçmiş": "Вся история",
  "Markasız": "Без бренда",
  "Kasasız": "Без кассы",
  "Kasaya bağlı": "Привязано к кассе",
  "Plan Kaynaklı": "Из плана",
  "Atanan kişi": "Исполнитель",
  "Yeni görev": "Новая задача",
  "Görevi sil": "Удалить задачу",
  "Bugünkü plan": "План на сегодня",
  "Açık görev": "Открытая задача",
  "Geciken görev": "Просроченная задача",
  "Yemek yardımı": "Питание",
  "Baz maaş": "Базовая ЗП",
  "Min ücret (USD)": "Мин. ставка (USD)",
  "Max ücret (USD)": "Макс. ставка (USD)",
  "Maks ücret (USD)": "Макс. ставка (USD)",
  "Bütçe (USD)": "Бюджет (USD)",
  "Aylık Maaş ($)": "Зарплата в месяц ($)",
  "Ödeme Günü": "День выплаты",
  "Ödeme günü": "День выплаты",
  "İşe Başlangıç": "Дата выхода",
  "Cüzdan Adresi": "Адрес кошелька",
  "Ayrılış tarihi": "Дата ухода",
  "Ayrılış nedeni": "Причина ухода",
  "İş çıkışı": "Увольнение",
  "Çalışanı düzenle": "Изменить сотрудника",
  "Satır içi düzenle": "Правка в строке",
  "Bekleyen Ödeme": "Ожидает выплаты",
  "Bekleyen onaylı": "Одобрено, ждёт выплаты",
  "Onaylı · Ödeme Bekliyor": "Одобрено · ждёт оплаты",
  "Ödendi mi?": "Оплачено?",
  "Yayıncı notu": "Заметка стримера",
  "Yönetici mesajı": "Сообщение админа",
  "Harcama ödendi": "Расход оплачен",
  "Harcamayı incele ve onayla": "Проверить и одобрить расход",
  "Harcama İncele & Onayla": "Проверка расхода",
  "Harcama Gönder": "Отправить расход",
  "İlk harcama gönder": "Отправить первый расход",
  "İlk harcamayı ekle": "Добавить первый расход",
  "İlk postu ekle": "Добавить первый пост",
  "İlk Hesabını Ekle": "Добавить первый аккаунт",
  "İlk faturayı oluştur": "Создать первый счёт",
  "İlk duyuruyu ekle": "Добавить первое объявление",
  "İlk üyeyi ekle": "Добавить первого участника",
  "İlk personeli ekle": "Добавить первого сотрудника",
  "İlk departmanı ekle": "Добавить первый отдел",
  "Fatura oluştur": "Создать счёт",
  "Ekip üyesi ekle": "Добавить в команду",
  "Teklif gönder": "Отправить оффер",
  "Teklifi geri çek": "Отозвать оффер",
  "Karşı teklif (USD)": "Контрпредложение (USD)",
  "Mesajınızı yazın…": "Напишите сообщение…",
  "Şablon seç": "Выбрать шаблон",
  "Şablonu uygula": "Применить шаблон",
  "Son uygulamayı geri al": "Отменить последнее",
  "Plan aç": "Открыть план",
  "Haftalık plan oluştur": "Создать недельный план",
  "Bu güne plan ekle": "Добавить план на день",
  "Profilini yayınla": "Опубликовать профиль",
  "Havuz profilini düzenle": "Изменить профиль пула",
  "İzlenmeye dön": "К просмотрам",
  "Videoyu aç": "Открыть видео",
  "İzlenme PDF": "PDF просмотров",
  "İzlenme raporu": "Отчёт по просмотрам",
  "Detaylı metrikler": "Подробные метрики",
  "Snapshot geçmişi": "История снимков",
  "Yayıncı izlenme": "Просмотры стримера",
  "Marka işlemleri": "Действия бренда",
  "Bu markanın paneline gir": "Открыть панель бренда",
  "Yayıncı paneline gir": "Открыть панель стримера",
  "Hesabına gir (denetim)": "Войти в аккаунт (аудит)",
  "En yüksek büyüme": "Наибольший рост",
  "En yüksek izlenme": "Больше всего просмотров",
  "En çok link": "Больше всего ссылок",
  "En çok marka": "Больше всего брендов",
  "Toplam yayıncı": "Всего стримеров",
  "Top yayıncı": "Топ стример",
  "Çoklu marka": "Несколько брендов",
  "Genel Özet": "Общая сводка",
  "Tüm linkler": "Все ссылки",
  "Platforma göre izlenme": "Просмотры по платформам",
  "Grafik türü": "Тип графика",
  "Pay dağılımı": "Распределение доли",
  "Karşılaştırma": "Сравнение",
  "Yığılı": "С накоплением",
  "Yüzde": "Процент",
  "artış": "рост",
  "Artış %": "Рост %",
  "İzlenme payı": "Доля просмотров",
  "İzlenme yükleniyor…": "Просмотры загружаются…",
  "Manuel İçerik Takibi": "Ручной учёт контента",
  "Bugün güncellenmemiş": "Сегодня не обновлялось",
  "API özetini yenile": "Обновить сводку API",
  "RapidAPI kapalı.": "RapidAPI выключен.",
  "API erişim sorunu.": "Проблема доступа к API.",
  "Bağlantıyı test et": "Проверить соединение",
  "RapidAPI erişilebilir": "RapidAPI доступен",
  "API kapsamı": "Покрытие API",
  "API dışı platformlar": "Платформы вне API",
  "Gönderi yok": "Нет постов",
  "Geçici limit": "Временный лимит",
  "Bu linki şimdi yenile": "Обновить эту ссылку сейчас",
  "Bu linki şimdi kontrol et": "Проверить эту ссылку сейчас",
  "Tüm linkleri kontrol et": "Проверить все ссылки",
  "Hiç kontrol edilmedi": "Ещё не проверялось",
  "Otomatik yenileme ayarları": "Настройки автообновления",
  "Aylık kota": "Месячная квота",
  "API bağlantısı": "Подключение API",
  "çalışıyor": "работает",
  "uyarı": "предупреждение",
  "kota tükendi": "квота исчерпана",
  "erişilebilir": "доступен",
  "erişilemiyor": "недоступен",
  "Platform API özellikleri — canlı test": "Возможности Platform API — живой тест",
  "Güncellenmeyen linkler": "Ссылки без обновления",
  "Toplu işlem:": "Пакетно:",
  "Sadece başarısızları": "Только ошибки",
  "Bildirim bölümleri": "Разделы уведомлений",
  "Bildirim akışı": "Лента уведомлений",
  "Bildirim Akışı": "Лента уведомлений",
  "Sessize alınan tipler": "Отключённые типы",
  "Kişisel tercihlerim": "Мои настройки",
  "Tek kullanıcı (opsiyonel)": "Один пользователь (необяз.)",
  "Bordro hatırlatıcı": "Напоминание о ведомости",
  "Kaç gün önceden": "За сколько дней",
  "Kasa düşük uyarısı (USDT eşiği)": "Низкий баланс кассы (порог USDT)",
  "Henüz bildirim yok.": "Уведомлений пока нет.",
  "Aylık Ödeme Raporu": "Месячный отчёт по выплатам",
  "Gider Kayıtları": "Записи расходов",
  "Gelir kaydı ekle": "Добавить доход",
  "Ödeme takvimi": "Календарь выплат",
  "Hatırlatma": "Напоминание",
  "Gelir payları": "Доли дохода",
  "Aylık tahmin": "Прогноз на месяц",
  "Yıllık karşılaştırma": "Годовое сравнение",
  "Yıllık İç Gelir": "Годовой внутр. доход",
  "Aylık Beklenen": "Ожидается за месяц",
  "Aktif Kayıt": "Активная запись",
  "Marka Bazlı Dağılım": "Разбивка по брендам",
  "Yayıncı / Rapor Eden": "Стример / автор",
  "İçerik tipi": "Тип контента",
  "İçerik URL": "URL контента",
  "İçerik linki": "Ссылка на контент",
  "Marka içerik URL": "URL контента бренда",
  "Snapshot ekle (izlenme güncelle)": "Добавить снимок (обновить просмотры)",
  "İzlenmeyi API ile çek": "Подтянуть просмотры через API",
  "Günlük istatistik ekle": "Добавить дневную статистику",
  "Günlük istatistik": "Дневная статистика",
  "Önce partner ekleyin": "Сначала добавьте партнёра",
  "Kayıt olan üye": "Зарегистрированные",
  "Yatırım yapan üye": "С депозитом",
  "İlk yatırım (FTD)": "Первый депозит (FTD)",
  "FTD sayısı": "Число FTD",
  "FTD tutarı": "Сумма FTD",
  "Komisyon (hak ediş)": "Комиссия",
  "Partner adı": "Имя партнёра",
  "Bu partnere ödeme ekle": "Добавить выплату партнёру",
  "Affiliate partner": "Affiliate-партнёр",
  "Affiliate tıklama": "Affiliate-клики",
  "Müzakere": "Переговоры",
  "İptal / Red": "Отмена / отказ",
  "Tamamlanmış teklif yok": "Нет завершённых офферов",
  "Şu an teklif yok": "Сейчас нет офферов",
  "Bütçe / Ödenen": "Бюджет / оплачено",
  "Ödenen (USD)": "Оплачено (USD)",
  "Ödeme tutarı (USD)": "Сумма выплаты (USD)",
  "Anlaşma düzenle": "Изменить сделку",
  "Kilometre taşları": "Вехи",
  "İhtilaflı": "Спор",
  "Uyuşmazlık": "Конфликт",
  "Kazanıldı": "Выиграно",
  "Kazanılan": "Выиграно",
  "Kazanma oranı": "Win rate",
  "Açık fırsat": "Открытая возможность",
  "Aşama": "Этап",
  "Olasılık (%)": "Вероятность (%)",
  "Tahmini kapanış": "Ожидаемое закрытие",
  "Beklenen aylık FTD": "Ожидаемый FTD / мес.",
  "Virgülle ayırın": "Через запятую",
  "Önem": "Важность",
  "henüz yok": "пока нет",
  "Yeni ekip üyesi": "Новый участник",
  "Üyeyi düzenle": "Изменить участника",
  "Üye": "Участник",
  "Rol dağılımı": "Распределение ролей",
  "Marka kapsamı": "Охват бренда",
  "API anahtarları": "Ключи API",
  "API erişimi": "Доступ API",
  "Import geçmişi": "История импорта",
  "Webhook logları": "Логи webhook",
  "Gönderildi olarak işaretle": "Отметить отправленным",
  "Ödendi olarak işaretle": "Отметить оплаченным",
  "Tutar (KDV hariç)": "Сумма (без НДС)",
  "Min takipçi": "Мин. подписчиков",
  "Max takipçi": "Макс. подписчиков",
  "Toplam takipçi": "Всего подписчиков",
  "Kampanya adı": "Название кампании",
  "Marka hesabı:": "Аккаунт бренда:",
  "Kaydı sil": "Удалить запись",
  "Toplam çalışma": "Всего работы",
  "Çıkış yaptı": "Вышел",
  "Gelir (USD eşdeğeri)": "Доход (экв. USD)",
  "Gider (USD eşдеğeri)": "Расход (экв. USD)",
  "GGR / operatör geliri": "GGR / доход оператора",
  "Tüm yönler": "Все направления",
  "Bu ay ödenecek": "К оплате в этом месяце",
  "Her şey hazır": "Всё готово",
  "Kurulumu tamamla ve panele geç.": "Завершите настройку и перейдите в панель.",
  "İstanbul (GMT+3)": "Стамбул (GMT+3)",
  "Kullanılan": "Использовано",
  "Görev yok.": "Нет задач.",
  "Durumu değiştir": "Сменить статус",
  "Toplam kişi": "Всего людей",
  "Yeni kayıt": "Новая запись",
  "İlerlet": "Продвинуть",
  "Sürekli haftalık şablon": "Повторяющийся недельный шаблон",
  "Geniş takvim görünümü": "Широкий календарь",
  "Haftalık grid": "Недельная сетка",
  "Plan & içerik": "План и контент",
  "Plan aç": "Открыть план",
  "Tüm bölümler": "Все разделы",
  "Yayıncı hızlı menü": "Быстрое меню стримера",
  "Kategori & ücret": "Категория и ставка",
  "Teklif gönder": "Отправить оффер",
  "Güncellenen Link": "Обновлённая ссылка",
  "Bu Ay Net Maaş": "Нетто ЗП в этом месяце",
  "Bu Ay Ödenen Toplam": "Всего выплачено в этом месяце",
  "Bu Ay Alınan Avans": "Аванс в этом месяце",
  "Ekstra Ödeme": "Доп. выплата",
  "Filtreleri sıfırla": "Сбросить фильтры",
  "Yöneticiye yanıt": "Ответ админу",
  "İzlenme toplamları": "Итоги просмотров",
  "Geçmiş Aylar Özeti": "Сводка прошлых месяцев",
  "Geçmiş kayıt yok.": "Нет истории.",
  "Tüm aktif linkler": "Все активные ссылки",
  "Net ödenecek (maaş)": "К выплате (зарплата)",
  "Tek liste (sıralı)": "Один список (по порядку)",
  "İzlenme (yüksek → düşük)": "Просмотры (больше → меньше)",
  "İzlenme (düşük → yüksek)": "Просмотры (меньше → больше)",
  "Toplam Beğeni": "Всего лайков",
  "Bordro Ödemeleri": "Выплаты по ведомости",
  "İzlenme haritası": "Карта просмотров",
  "İzlenme panosu": "Дашборд просмотров",
  "İzlenme Panosu": "Дашборд просмотров",
  "Zaman çizelgesi": "Таймлайн",
  "Dosya seç": "Выбрать файл",
  "İçe aktarım tamamlandı": "Импорт завершён",
  "Gerekli başlık": "Обязательный заголовок",
  "İhtiyaç halinde açın": "Откройте при необходимости",
  "Kümülatif alan": "Накопительная область",
  "Marka trendleri · çoklu çizgi": "Тренды брендов · несколько линий",
  "Hızlı:": "Быстро:",
  "YouTube türü": "Тип YouTube",
  "Hashtag sıralaması": "Рейтинг хештегов",
  "Yayın zamanı": "Время эфира",
  "Takipçi aralığı": "Диапазон подписчиков",
  "Profil türü": "Тип профиля",
  "Arama odağı": "Фокус поиска",
  "Sonuç sıralama": "Сортировка результатов",
  "Hesaplarım": "Мои аккаунты",
  "İçerik türü": "Тип контента",
  "Hedef yayıncı": "Целевой стример",
  "Tüm plan geçmişi": "Вся история планов",
  "Tüm aktiviteler": "Все активности",
  "Önizlemeyi oynat": "Смотреть превью",
  "Tarih aralığı": "Диапазон дат",
  "Başlatan": "Инициатор",
  "İlk mesaj (opsiyonel)": "Первое сообщение (необяз.)",
  "Sistem hazırlanıyor": "Система готовится",
  "Yayıncı marka linkleri": "Ссылки брендов стримера",
  "İçerikler yükleniyor…": "Контент загружается…",
  "Güncel seri": "Текущая серия",
  "Bu ay paylaşım": "Публикации в этом месяце",
  "Toplam içerik": "Всего контента",
  "Anlaşma (opsiyonel)": "Сделка (необяз.)",
  "Açıklama / caption": "Описание / подпись",
  "İzlenme (manuel)": "Просмотры (вручную)",
  "Beğeni (manuel)": "Лайки (вручную)",
  "— Bağımsız —": "— Независимо —",
  "Gerçek ad": "Настоящее имя",
  "Kitle büyüklüğü": "Размер аудитории",
  "Link kaydı": "Запись ссылки",
  "Onaylı / ödeme": "Одобрено / выплата",
  "Bordro masrafı": "Расход в ведомости",
  "Ay toplamı (aktif)": "Итого за месяц (актив)",
  "Onaylı tutar": "Одобренная сумма",
  "Bordroya bağlı": "В ведомости",
  "Paylaşımlar & check-in": "Публикации и check-in",
  "En çok izlenen linkler": "Самые просматриваемые ссылки",
  "Son paylaşımlar": "Последние публикации",
  "Planı ata": "Назначить план",
  "Varsayılan kişi": "Человек по умолчанию",
  "Varsayılan personel": "Персонал по умолчанию",
  "Atanan yayıncılara bildirim gönder": "Уведомить назначенных стримеров",
  "Yıl": "Год",
  "Üst kontroller": "Верхние элементы",
  "API kapalı": "API выключен",
  "API hatası": "Ошибка API",
  "Link yenileme uyarısı": "Предупреждение обновления ссылок",
  "Aylık kota neredeyse doldu": "Месячная квота почти исчерпана",
  "API'den çekiliyor…": "Загрузка из API…",
  "Etkileşim oranı (premium)": "ER (premium)",
  "Kullanılan ses": "Использованный звук",
  "Video / içerik adı": "Название видео / контента",
  "Görünen başlık": "Отображаемый заголовок",
  "Yayıncı / operatör": "Стример / оператор",
  "URL henüz yok": "URL ещё нет",
  "Detay & API'den çek": "Детали и загрузка из API",
  "Marka atanmamış": "Бренд не назначен",
  "Veri aralığı": "Диапазон данных",
  "Rapor ayı seç": "Выберите месяц отчёта",
  "Yazdırılabilir profesyonel rapor": "Печатный профессиональный отчёт",
  "Ödemeler": "Выплаты",
  "Taksitler ve ödeme durumu": "Рассрочка и статус оплаты",
  "Yatırım hedefi": "Цель по депозитам",
  "Kayıt hedefi": "Цель по регистрациям",
  "İçerik teslim": "Сдача контента",
  "Düşük demo bakiye": "Низкий демо-баланс",
  "Görebilirsiniz:": "Можно:",
  "Yapamazsınız:": "Нельзя:",
  "Birleşik dışa aktarım": "Единый экспорт",
  "Paylaşım günü": "День публикации",
  "Paylaşım günleri": "Дни публикаций",
  "Partner yayıncı": "Партнёр-стример",
  "Teklif öncesi uyumluluk kontrolü": "Проверка комплаенса до оффера",
  "Tüm · aylık": "Все · месяц",
  "Tüm · toplam": "Все · всего",
  "Yeni · aylık": "Новые · месяц",
  "Hariç tut": "Исключить",
  "Hariç tutulan": "Исключённые",
  "Hariç": "Кроме",
  "Yeni kişi ekle": "Добавить человека",
  "Hızlı dağıtım": "Быстрое распределение",
  "Dağıtım detay": "Детали распределения",
  "Marka ücretleri": "Плата брендов",
  "Para akışı": "Денежный поток",
  "Kim ne alır": "Кто что получает",
  "Prim sonrası": "После премии",
  "Prim sonrası kâr": "Прибыль после премии",
  "İzlenme primi": "Премия за просмотры",
  "Gelir çarpanı": "Множитель дохода",
  "Gider çarpanı": "Множитель расходов",
  "İzlenme çarpanı": "Множитель просмотров",
  "Güvenlik kontrolleri": "Проверки безопасности",
  "Havuz tabanı": "Пол пула",
  "Kişi başı sınır": "Лимит на человека",
  "Toplam sınır": "Общий лимит",
  "Hazır sistemler": "Готовые системы",
  "Özel senaryo (ne olursa?)": "Свой сценарий (что если?)",
  "Öngörülen prim": "Прогноз премии",
  "Öngörülen toplam prim": "Прогноз общей премии",
  "Gerçek veri": "Факт",
  "Dağıtılabilir": "К распределению",
  "Ücret $": "Плата $",
  "Önceki ayı kopyala": "Копировать прошлый месяц",
  "Adım boyutu (örn. 1M)": "Шаг (напр. 1M)",
  "Kasa payı:": "Доля кассы:",
  "Net havuz payı:": "Доля чистого пула:",
  "İzlenme havuz bonusu:": "Бонус пула просмотров:",
  "Marka ücret & garanti": "Плата бренда и гарантия",
  "Reklam & diğer giderler (elle)": "Реклама и прочие расходы (вручную)",
  "Net havuz (gelir − tüm giderler)": "Чистый пул (доход − все расходы)",
  "Toplam kenara ayrılan": "Всего в резерве",
  "Taban altında mı?": "Ниже пола?",
  "Özel": "Свой",
  "Kaydırıcılarla özelleştirilmiş": "Настроено слайдерами",
  "Garanti aşımı": "Превышение гарантии",
  "Kişilere bölüşüm": "Деление по людям",
  "Bölüşüm": "Деление",
  "Yükle": "Загрузить",
  "Kanıtı temizle": "Очистить доказательство",
  "Oturum yakında kapanacak": "Сессия скоро закроется",
  "Aktif markayı değiştir": "Сменить активный бренд",
  "Yönetim Paneli": "Панель управления",
  "Maaşlar (Read)": "Зарплаты (чтение)",
  "7s şablon": "7с шаблон",
  "7 saniye şablon · haftalık plan": "7-сек. шаблон · недельный план",
  "Güncel Hesaplar": "Текущие аккаунты",
  "Yayın Slotu": "Слот эфира",
  "Haftalık Yayın Planı": "Недельный план эфиров",
  "Yayıncı Haftalık Planları": "Недельные планы стримеров",
  "Takvim yükleniyor…": "Календарь загружается…",
  "Yayıncı planı": "План стримера",
  "Yayıncı planları": "Планы стримеров",
  "Günlük içerik check-in": "Ежедневный check-in контента",
  "Sayfa içi hızlı gezinme": "Быстрая навигация по странице",
  "Postlarım / anlaşma": "Мои посты / сделка",
  "ekle": "добавить",
  "aç": "открыть",
  "kullanın.": "используйте.",
  "yayıncı": "стример",
  "Kayıt Sayısı": "Число регистраций",
  "Toplam kayıt": "Всего регистраций",
  "Toplam yatırım": "Всего депозитов",
  "Toplam çekim": "Всего выводов",
  "Yatırım yapan": "С депозитом",
  "En yüksek ay": "Лучший месяц",
  "Düşük bakiye": "Низкий баланс",
  "Marka onaylandı": "Бренд одобрен",
  "Yayıncı onaylandı": "Стример одобрен",
  "Yinelenmiş": "Дубликат",
  "ay bazlı": "по месяцам",
  "Çalışan": "Сотрудник",
  "Başlangıç ayı": "Месяц начала",
  "Bitiş ayı": "Месяц окончания",
  "Toplu kira düzenle": "Массово изменить аренду",
  "Geçerli ay seçilmedi.": "Месяц не выбран.",
  "Supabase kaydı başarısız": "Ошибка записи Supabase",
  "Aylık hacim": "Месячный объём",
  "İletişim kişisi": "Контактное лицо",
  "18+ yaş uyarısı ve hedef kitle uyumu": "Предупреждение 18+ и соответствие аудитории",
  "Bonus ve promosyon kuralları paylaşıldı": "Правила бонусов переданы",
  "Şüpheli yatırım artışı": "Подозрительный рост депозитов",
  "Şüpheli çekim artışı": "Подозрительный рост выводов",
  "Fraud bayrakları ve checklist durumu": "Флаги фрода и чеклист",
  "Yanıt bekleyen yayıncı teklifleri": "Офферы, ждущие ответа стримера",
  "Yetkiye bağlı modül": "Модуль по правам",
  "Kayıt, FTD, yatırım/çekim KPI": "KPI: регистрации, FTD, депозит/вывод",
  "Link, yayıncı ve içerik özeti": "Сводка ссылок, стримеров и контента",
  "Değişim (ilk seri)": "Изменение (первый ряд)",
  "Seçili ayda link bazlı Views": "Просмотры по ссылкам за выбранный месяц",
  "Marka modül grupları": "Группы модулей бренда",
  "Bu ayın izlenme snapshot": "Снимок просмотров этого месяца",
  "Önceki kayıt:": "Предыдущая запись:",
  "İçerik:": "Контент:",
  "Kontrol ettiğiniz gün": "День проверки",
  "Platformdaki güncel kümülatif sayı": "Текущий накопительный счётчик на платформе",
  "Kampanya, yayın adı, ek açıklama": "Кампания, название эфира, доп. описание",
  "TXID / Blockchain Kanıtı": "TXID / доказательство в блокчейне",
  "TXID, URL veya doğrudan resim yükle": "TXID, URL или загрузить изображение",
  "Kanıt (TXID / Dekont / Ekran görüntüsü)": "Доказательство (TXID / чек / скрин)",
  "Kanıt (Resim yükle veya URL)": "Доказательство (фото или URL)",
  "Dekont/ekran görüntüsü": "Чек / скриншот",
  "Amaç / Açıklama": "Назначение / описание",
  "İsim / cüzdan": "Имя / кошелёк",
  "Etiket gir (ör. isim)": "Метка (напр. имя)",
  "İzleme başlangıcı": "Начало отслеживания",
  "Takip başlangıç tarihi": "Дата начала учёта",
  "Tümünü dahil et": "Включить все",
  "Tümünü çıkar": "Исключить все",
  "Sonrasını dahil et": "Включить последующие",
  "Sonrasını çıkar": "Исключить последующие",
  "Geçmişten doldur:": "Заполнить из истории:",
  "USDT cüzdan": "Кошелёк USDT",
  "Banka hesabı": "Банковский счёт",
  "↓ Gelen (kasaya giriş)": "↓ Вход (в кассу)",
  "↑ Giden (kasadan çıkış)": "↑ Выход (из кассы)",
  "PIN Hazır": "PIN готов",
  "Paylaşım önizlemesi": "Превью для передачи",
  "İşlem günlüğü": "Журнал действий",
  "Yedek yükle": "Загрузить бэкап",
  "İsme göre (A→Z)": "По имени (А→Я)",
  "Role göre": "По роли",
  "Son girişe göre": "По последнему входу",
  "Aktif önce": "Сначала активные",
  "henüz giriş yok": "ещё не входил",
  "Yönetici Yetkileri": "Права администратора",
  "Kullanıcılar yükleniyor…": "Пользователи загружаются…",
  "Bağlı Yayıncı (Employee)": "Связанный стример",
  "Bağlı marka": "Связанный бренд",
  "— Bağsız —": "— Без связи —",
  "Pasif (giriş yapamaz)": "Неактивен (вход закрыт)",
  "7 gün": "7 дней",
  "30 gün": "30 дней",
  "90 gün": "90 дней",
  "Tüm eylemler": "Все действия",
  "Sıralı havuz": "Упорядоченный пул",
  "tıkla = ekle": "клик = добавить",
  "Başlık (opsiyonel)": "Заголовок (необяз.)",
  "Detayları göster": "Показать детали",
  "kapanıyor": "закрывается",
  "Düzenlemek için çift tıkla": "Двойной клик для правки",
  "ör.": "напр.",
  "Örn.": "Напр.",
  "Ör.": "Напр.",
  "Örnek": "Пример",
  "Boş bırakılırsa otomatik üretilir": "Если пусто — сгенерируется",
  "Otomatik üretilecek": "Будет сгенерировано",
  "Marka Başvuruları": "Заявки брендов",
  "Yayıncı Başvuruları": "Заявки стримеров",
  "Maaş Bordrosu": "Зарплатная ведомость",
  "Plan Toplamı": "Итого плана",
  "Ödenen Toplam": "Всего выплачено",
  "İçerik (onaylı)": "Контент (одобрен)",
  "İçerik (bordro)": "Контент (ведомость)",
  "Gerçekleşen": "Факт",
  "Oluşturma": "Создание",
  "Kısmi": "Частично",
  "Düzenleme tarihi": "Дата изменения",
  "sayfasından ekip üyesi ekleyin.": "добавьте участника со страницы.",
  "Tüm kalemler ödendi": "Все позиции оплачены",
  "Kullanıcı Adı / Handle": "Ник / handle",
  "Çalışan bulunamadı": "Сотрудник не найден",
  "Başlık (headline)": "Заголовок",
  "1 yıl": "1 год",
  "Net yatırım": "Чистые инвестиции",
  "İçerik harcaması (pay)": "Расход на контент (доля)",
  "Yayıncı:": "Стример:",
  "Tür:": "Тип:",
  "Gönderim:": "Отправка:",
  "Uyarı (3-6g)": "Внимание (3–6д)",
  "Açıklama veya marka...": "Описание или бренд...",
  "Açıklama / marka ara": "Поиск описания / бренда",
  "Açıklama / kategori ara…": "Поиск описания / категории…",
  "Anlaşma detayları...": "Детали сделки...",
  "Hangi içerik, hangi gider...": "Какой контент, какой расход...",
  "Kısa, net bir açıklama yaz…": "Коротко и ясно…",
  "Site Videoları": "Видео сайта",
  "Link hatası": "Ошибка ссылки",
  "Henüz sponsor işlemi yok.": "Спонсорских операций пока нет.",
  "Filtreyle eşleşen firma yok.": "Нет фирм по фильтру.",
  "Filtreyle eşleşen personel yok.": "Нет персонала по фильтру.",
  "Geçmişe yönelik gelir kayıtları": "Исторические записи дохода",
  "Yayıncı + admin aktivitesi": "Активность стримера и админа",
  "Yayıncı / Rapor Eden": "Стример / автор",
  "Sunucuya gönderiliyor…": "Отправка на сервер…",
  "Bu güne plan ekle": "План на этот день",
  "Bu ay dağıtılacak prim": "Премия к выплате в этом месяце",
  "Marka geliri (brüt)": "Доход бренда (брутто)",
  "Oran neye uygulansın?": "К чему применить долю?",
  "Karşılamayı kapat": "Закрыть покрытие",
  "⚠ Kasa düşük bakiye uyarısı": "⚠ Низкий баланс кассы",
  "Özel PIN (opsiyonel)": "Свой PIN (необяз.)",
  "Kullanıcı adı (tercih)": "Ник (предпочтение)",
  "Kullanıcı adı (opsiyonel override)": "Ник (переопределение)",
  "bir daha gösterilmeyecek": "больше не показывать",
  "İlk yatırım (FTD)": "Первый депозит (FTD)",
  "Kayıt olan üye": "Зарегистрированные",
  "Yatırım yapan üye": "С депозитом",
  "Günlük istatistik ekle": "Добавить дневную статистику",
  "Önce partner ekleyin": "Сначала добавьте партнёра",
  "Planlandı": "Запланировано",
  "Takipçi": "Подписчики",
  "Geçmiş aylar": "Прошлые месяцы",
  "Maaş": "Зарплата",
  "Operasyon özeti": "Сводка операций",
  "Max ücret (USD)": "Макс. ставка (USD)",
  "Min ücret (USD)": "Мин. ставка (USD)",
  "Kaldır": "Убрать",
  "Bütçe (USD)": "Бюджет (USD)",
  "PIN sıfırla": "Сбросить PIN",
  "Aramayı temizle": "Очистить поиск",
  "Marka adı": "Название бренда",
  "Sıralama": "Сортировка",
  "Aylık rapor": "Месячный отчёт",
  "Dönem": "Период",
  "Marka İzlenme": "Просмотры бренда",
  "Yayıncılar": "Стримеры",
  "Ekle": "Добавить",
  "Erişim Yok": "Нет доступа",
  "Ödeme Raporu": "Отчёт по выплатам",
  "Yüksek": "Высокий",
  "Düşük": "Низкий",
  "Geri": "Назад",
  "Bütçe": "Бюджет",
  "Tüm yayıncılar": "Все стримеры",
  "Kullanıcı adı": "Имя пользователя",
  "İçerik": "Контент",
  "Atanmamış": "Не назначено",
  "Anlaşma": "Сделка",
  "Toplam": "Итого",
  "Tür": "Тип",
  "Operatörler": "Операторы",
  "Link": "Ссылка",
  "Onayla": "Одобрить",
  "Reddet": "Отклонить",
  "Kapat": "Закрыть",
  "Açık Avans": "Открытый аванс",
  "Önceki ay": "Прошлый месяц",
  "Aç": "Открыть",
  "İşlem": "Действие",
  "Gecikmiş": "Просрочено",
  "Ödenen": "Оплачено",
  "Çekim": "Вывод",
  "Tıklama": "Клики",
  "Linki aç": "Открыть ссылку",
  "Paylaşım": "Публикация",
  "Ödeme tarihi": "Дата оплаты",
  "Tüm markalar": "Все бренды",
  "İçerik Harcamaları": "Расходы на контент",
  "Tamamlandı": "Завершено",
  "Diğer": "Другое",
  "Öncelik": "Приоритет",
  "Yatırım": "Депозит",
  "Görevler": "Задачи",
  "Bitiş": "Конец",
  "Beğeni": "Лайки",
  "Ödendi": "Оплачено",
  "Başlangıç": "Начало",
  "Başlık": "Заголовок",
  "Kayıt": "Регистрация",
  "Pasif": "Неактивен",
  "İptal": "Отмена",
  "Yayıncı": "Стример",
  "Açıklama": "Описание",
  "Aktif": "Активен",
  "İzlenme": "Просмотры",
  "Düzenle": "Изменить",
  "Yükleniyor…": "Загрузка…",
  "Tümü": "Все",
  "Sil": "Удалить",
  "Onaylı": "Одобрено",
  "Etkileşim": "Вовлечённость",
  "pasif": "неактивен",
  "Görünen ad": "Отображаемое имя",
  "Premium keşif": "Premium-поиск",
  "İstatistikler": "Статистика",
  "İzlenmeler": "Просмотры",
  "İçerik URL": "URL контента",
  "Geniş ekran": "Широкий экран",
  "Önceki hafta": "Прошлая неделя",
  "Aylık hedef": "Месячная цель",
  "Çıkış": "Выйти",
  "Kira Desteği": "Жилищная поддержка",
  "Kira desteği": "Жилищная поддержка",
  "Yayıncı:": "Стример:",
  "İç Gelir": "Внутренний доход",
  "Kayıt yok": "Нет записей",
};

function walk(dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, acc);
    else if (e.name.endsWith(".tsx")) acc.push(p);
  }
  return acc;
}

function collectStrings() {
  const files = [...walk("src/app"), ...walk("src/components")].filter(
    (f) => !f.includes("/login/") && !f.includes("/landing/") && !f.includes("locale-"),
  );
  const TR = /[ğıüşöçİĞÜŞÖÇ]/;
  const set = new Set();
  const add = (s, force = false) => {
    s = s.replace(/\s+/g, " ").trim();
    if (s.length < 2 || s.length > 160) return;
    if (s.startsWith("http") || s.startsWith("/") || s.startsWith("bg-") || s.startsWith("text-")) return;
    if (force || TR.test(s) || G[s]) set.add(s);
  };
  for (const file of files) {
    const src = fs.readFileSync(file, "utf8");
    for (const m of src.matchAll(/>([^<>{}]+)</g)) add(m[1]);
    for (const m of src.matchAll(/(?:title|subtitle|description|label|placeholder|aria-label|badge|header|hint|emptyText|ctaLabel|buttonLabel)=\{?["'`]([^"'`]{1,160})["'`]/g)) add(m[1], true);
    for (const m of src.matchAll(/(?:title|subtitle|description|label|placeholder|header|hint):\s*["'`]([^"'`]{1,160})["'`]/g)) add(m[1], true);
  }
  return [...set];
}

const phrases = Object.entries(G).sort((a, b) => b[0].length - a[0].length);
const LETTER = /\p{L}/u;

function translate(input) {
  if (G[input]) return G[input];
  let i = 0;
  let out = "";
  while (i < input.length) {
    let hit = null;
    const prevOk = i === 0 || !LETTER.test(input[i - 1]);
    if (prevOk) {
      for (const [tr, ru] of phrases) {
        if (!input.startsWith(tr, i)) continue;
        const next = input[i + tr.length];
        if (next && LETTER.test(next)) continue;
        hit = [tr, ru];
        break;
      }
    }
    if (hit) {
      out += hit[1];
      i += hit[0].length;
    } else {
      out += input[i];
      i++;
    }
  }
  return out;
}

const strings = collectStrings();
const exact = { ...G };
for (const s of strings) {
  if (exact[s]) continue;
  const ru = translate(s);
  if (ru !== s) exact[s] = ru;
}

fs.writeFileSync("src/lib/i18n/ui-ru.json", JSON.stringify({ UI_RU: exact, UI_PHRASES: phrases }));
console.log("wrote src/lib/i18n/ui-ru.json", "exact", Object.keys(exact).length, "phrases", phrases.length, "scanned", strings.length);
